version: '3.7'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app:rw
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: coronavirus
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /tmp/mongo/corona-growth:/data/db
volumes:
  mongodbdata: {}
