export const RESET_STATE = 'RESET_STATE';
export const SET_TAB = 'SET_TAB';

/** Country Types */
export const SET_COUNTRY_FILTER = 'SET_COUNTRY_FILTER';
export const SET_COUNTRY_DATA_TYPE = 'SET_COUNTRY_DATA_TYPE';
export const SET_COUNTRY_TIME_TYPE = 'SET_COUNTRY_TIME_TYPE';

export const SET_ALL_COUNTRIES_DATA_TYPE = 'SET_ALL_COUNTRIES_DATA_TYPE';
export const SET_ALL_COUNTRIES_SELECTED = 'SET_ALL_COUNTRIES_SELECTED';
export const SET_ALL_COUNTRIES_FILTER = 'SET_ALL_COUNTRIES_FILTER';

/** Region Types */
export const SET_REGION_FILTER = 'SET_REGION_FILTER';
export const SET_REGION_DATA_TYPE = 'SET_REGION_DATA_TYPE';
export const SET_REGION_TIME_TYPE = 'SET_REGION_TIME_TYPE';

export const SET_ALL_REGIONS_DATA_TYPE = 'SET_ALL_REGIONS_DATA_TYPE';
export const SET_ALL_REGIONS_SELECTED = 'SET_ALL_REGIONS_SELECTED';
export const SET_ALL_REGIONS_FILTER = 'SET_ALL_REGIONS_FILTER';
