export const SET_COUNTRY_FILTER = 'SET_COUNTRY_FILTER';
export const SET_COUNTRY_DATA_TYPE = 'SET_COUNTRY_DATA_TYPE';
export const SET_COUNTRY_TIME_TYPE = 'SET_COUNTRY_TIME_TYPE';

export const RESET_STATE = 'RESET_STATE';

export const SET_ALL_COUNTRIES_DATA_TYPE = 'SET_ALL_COUNTRIES_DATA_TYPE';
export const SET_ALL_COUNTRIES_SELECTED = 'SET_ALL_COUNTRIES_SELECTED';

export const SET_REGION_DATA_TYPE = 'SET_REGION_DATA_TYPE';
